const noCommentsPlugin = require('eslint-plugin-no-comments');

module.exports = [
  {
    ignores: [
      'node_modules/**',
      '.expo/**',
      '.expo-shared/**',
      'assets/**',
      'metro.config.js',
      'babel.config.js',
    ],
  },
  {
    files: ['**/*.js', '**/*.jsx'],
    plugins: {
      'no-comments': noCommentsPlugin,
      i18next: require('eslint-plugin-i18next'),
      react: require('eslint-plugin-react'),
    },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        module: 'readonly',
        fetch: 'readonly',
        alert: 'readonly',
        require: 'readonly',
        global: 'readonly',
        __DEV__: 'readonly',
        Expo: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        jest: 'readonly',
      },
    },
    rules: {
      'no-multiple-empty-lines': ['error', { max: 1, maxEOF: 1 }],
      'no-console': 'error',
      'no-comments/disallowComments': 'error',
      'max-lines-per-function': ['warn', 50],
      complexity: ['warn', 10],
      'react/jsx-max-depth': ['warn', { max: 4 }],
      'i18next/no-literal-string': [
        'error',
        {
          ignore: [
            '',
            /^[a-zA-Z]$/,
            /^[\d\s\.\-\+\=\<\>\[\]\(\)\{\}\*\+\?\^\$\|\\]*$/,
            /^https?:\/\//,
            /^\/\w+/,
            /^[a-zA-Z][a-zA-Z0-9\-_]*$/,
            /^(import|export|from|require)$/,
            /^[A-Z][a-zA-Z0-9]*$/,
            /^(true|false|null|undefined|function|const|let|var|if|else|for|while|do|switch|case|default|try|catch|finally|throw|return|break|continue)$/,
            /\.(js|jsx|ts|tsx|json|css|scss|html|xml)$/,
            /^(id|url|api|http|https|www|com|org|net|io)$/i,
            /^\d+\.\d+\.\d+$/,
            /^\d{1,2}:\d{2}$/,
            /^\d{1,2}\/\d{1,2}\/\d{4}$/,
            /^\+?\d[\d\s\-\(\)]+$/,
            /^@\w+\.\w+$/,
          ],
          ignoreCallee: [
            'console.log',
            'console.error',
            'console.warn',
            'console.info',
            'StyleSheet.create',
            'require',
            'import',
          ],
          ignoreAttribute: [
            'key',
            'testID',
            'accessibilityLabel',
            'accessibilityHint',
            'placeholder',
            'style',
            'className',
            'id',
            'name',
            'type',
            'value',
            'defaultValue',
            'src',
            'href',
            'alt',
            'title',
            'role',
            'aria-label',
            'aria-describedby',
            'data-testid',
            'data-cy',
          ],
        },
      ],
    },
  },
  {
    files: ['**/*.test.js', '**/*.spec.js', '__tests__/**/*.js'],
    rules: {
      'no-console': 'off',
      'no-comments/disallowComments': 'off',
      'i18next/no-literal-string': 'off',
    },
  },
];
